### ISSUE TITLE
Fix Northern, Southern, and Central regions

### ISSUE THREAD

**Issue by aazaff** [UW-Macrostrat/gill#2]
There are several regions with the name "Northern" etc. The https://dev.macrostrat.org/api/places?name=Northern. We should bind these regions with their respective country name - e.g., the region Northern in the country Fiji should be renamed to Northern Fiji

**Comment by jczaplew** [comment]
Seems reasonable.

**Comment by jczaplew** [comment]
Fixed.

**Comment by aazaff** [comment]
Curse you, Western, NE
